export const DEFAULT_CONFIG: QueryBuilderConfig = {
  tables: {
    daily_agg: {
      name: 'daily_agg',
      timeColumn: 'date',
      timeWindowsAvailable: ['day', 'week', 'month', 'quarter', 'year'],
      validMetrics: new Set(['close', 'high', 'low', 'open', 'volume', 'trades']),
      primaryKeys: ['ticker', 'date'],
      alwaysIncludeColumns: ['ticker', 'date', 'close'],
    },
    tickers: {
      name: 'tickers',
      timeColumn: 'date',
      timeWindowsAvailable: ['day', 'week', 'month', 'quarter', 'year'],
      validMetrics: new Set(['market_cap', 'sector', 'industry', 'country']),
      primaryKeys: ['ticker'],
      otherColumns: ['name', 'currency', 'sic_code', 'primary_exchange'],
      alwaysIncludeColumns: ['ticker', 'name'],
    },
  },
  columnMappings: {
    symbol: { table: 'tickers', column: 'ticker', type: 'String', timeseries: false },
    ticker: { table: 'tickers', column: 'ticker', type: 'String', timeseries: false },
    price: { table: 'daily_agg', column: 'close', type: 'Float64', timeseries: true },
    adjusted_price: { table: 'daily_agg', column: 'close', type: 'Float64', timeseries: true },
    close: { table: 'daily_agg', column: 'close', type: 'Float64', timeseries: true },
    adjusted_close: { table: 'daily_agg', column: 'close', type: 'Float64', timeseries: true },
    high: { table: 'daily_agg', column: 'high', type: 'Float64', timeseries: true },
    low: { table: 'daily_agg', column: 'low', type: 'Float64', timeseries: true },
    open: { table: 'daily_agg', column: 'open', type: 'Float64', timeseries: true },
    volume: { table: 'daily_agg', column: 'volume', type: 'Float64', timeseries: true },
    trades: { table: 'daily_agg', column: 'trades', type: 'Float64', timeseries: true },
    market_cap: {
      table: 'tickers',
      column: 'market_cap',
      type: 'String',
      timeseries: true,
    },
    sector: {
      table: 'tickers',
      column: 'sector',
      type: 'String',
      timeseries: false,
    },
    industry: {
      table: 'tickers',
      column: 'industry',
      type: 'String',
      timeseries: false,
    },
    active: {
      table: 'tickers',
      column: 'active',
      type: 'UInt8',
      timeseries: true,
    },
    country: {
      table: 'tickers',
      column: 'country',
      type: 'String',
      timeseries: false,
    },
  },
  timeFormat: 'date',
  maxTimeseriesWindow: 365 * 5,
  maxLimit: 10000,
};
